tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "primary-fixed": "#f7e382",
                    "tertiary": "#d0cdcd",
                    "tertiary-fixed-dim": "#c8c6c5",
                    "error-container": "#93000a",
                    "on-secondary": "#313030",
                    "on-secondary-container": "#bab8b7",
                    "tertiary-container": "#b4b2b2",
                    "surface-container-lowest": "#0d0e0f",
                    "primary": "#e2cf70",
                    "on-tertiary-fixed": "#1b1c1c",
                    "on-tertiary-container": "#454545",
                    "on-error-container": "#ffdad6",
                    "surface-container-highest": "#343535",
                    "on-primary-fixed-variant": "#524700",
                    "surface-bright": "#383939",
                    "surface-container-high": "#292a2a",
                    "on-tertiary-fixed-variant": "#474746",
                    "primary-fixed-dim": "#dac769",
                    "on-primary-fixed": "#211b00",
                    "secondary": "#c8c6c5",
                    "on-secondary-fixed": "#1c1b1b",
                    "surface-container-low": "#1b1c1c",
                    "surface-tint": "#dac769",
                    "outline": "#96917f",
                    "error": "#ffb4ab",
                    "secondary-container": "#4a4949",
                    "on-tertiary": "#303030",
                    "on-secondary-fixed-variant": "#474646",
                    "surface-variant": "#343535",
                    "primary-container": "#c5b358",
                    "outline-variant": "#4b4738",
                    "inverse-on-surface": "#2f3031",
                    "background": "#121414",
                    "surface-dim": "#121414",
                    "tertiary-fixed": "#e4e2e1",
                    "on-error": "#690005",
                    "secondary-fixed-dim": "#c8c6c5",
                    "on-surface-variant": "#cdc6b3",
                    "secondary-fixed": "#e5e2e1",
                    "on-surface": "#e3e2e2",
                    "inverse-primary": "#6c5e06",
                    "on-background": "#e3e2e2",
                    "surface-container": "#1f2020",
                    "on-primary-container": "#504500",
                    "surface": "#121414",
                    "inverse-surface": "#e3e2e2",
                    "on-primary": "#393000"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "unit": "8px",
                    "margin-desktop": "80px",
                    "gutter": "32px",
                    "margin-mobile": "24px",
                    "container-max": "1200px"
            },
            "fontFamily": {
                    "headline-md": ["Bodoni Moda"],
                    "label-caps": ["Hanken Grotesk"],
                    "body-md": ["Hanken Grotesk"],
                    "headline-sm": ["Bodoni Moda"],
                    "body-lg": ["Hanken Grotesk"],
                    "display-lg": ["Bodoni Moda"],
                    "display-lg-mobile": ["Bodoni Moda"]
            },
            "fontSize": {
                    "headline-md": ["32px", {"lineHeight": "1.3", "letterSpacing": "0.02em", "fontWeight": "400"}],
                    "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.2em", "fontWeight": "600"}],
                    "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "400"}],
                    "headline-sm": ["24px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
                    "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "300"}],
                    "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400"}],
                    "display-lg-mobile": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "400"}]
            }
          },
        },
      }